version: 0.2

phases:
  install:
    runtime-versions:
      php: 8.2

  pre_build:
    on-failure: ABORT
    commands:
      - echo "logging in to Amazon ECR ..."
     # - aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin $REPOSITORY
      - aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin 147726474727.dkr.ecr.us-east-1.amazonaws.com
      
  build:
    on-failure: ABORT
    commands:
      - docker build -t $IMAGE
      - docker tag $IMAGE:$IMAGE_TAG $REPOSITORY/$IMAGE:$IMAGE_TAG

  post_build:
    on-failure: ABORT
    commands:
      - docker images ls -a
      - docker push $REPOSITORY/$IMAGE:$IMAGE_TAG
