version: 0.2

phases:
  install:
    runtime-versions:
      php: 8.2

  pre_build:
    commands:
      - echo "logging in to Amazon ECR ..."
      - aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin $REPOSITORY

  build:
    commands:
      - docker build -t $IMAGE
      - docker tag $IMAGE_TAG:$REPOSITORY/$IMAGE:$IMAGE_TAG

  post_build:
    commands:
      - docker images ls -a
      - docker push $REPOSITORY/$IMAGE:$IMAGE_TAG
